name: Release a new Docker image

on:
  push:
    branches: [ main ]
    paths: [ "Cargo.toml" ]
  workflow_dispatch: {}
permissions:
    contents: write
    packages: write
jobs:
  tag:
    name: Define Tags for version in Cargo.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=v$(cargo metadata --no-deps --quiet | jq -r '.packages | last | .version')

          git fetch --tags

          if [ $(git tag -l $TAG) ]
          then
            echo "Git tag $TAG already exists."
          else
            git config user.name "Add Tag from CI"
            git config user.email ""
            git tag $TAG
            git push --tags
          fi

          gh release view $TAG &> /dev/null || gh release create $TAG -d --notes $TAG
  image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch label
        run: echo "LABEL=v$(cargo metadata --no-deps --quiet | jq -r '.packages | last | .version')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |-
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.LABEL }}
